In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/flight_data_cleaned.csv")
data.head(10)

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,duration_category
0,SpiceJet,1408,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,Medium
1,SpiceJet,1387,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,Long
2,AirAsia,1213,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,Medium
3,Vistara,1559,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,Medium
4,Vistara,1549,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,Long
5,Vistara,1541,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955,Long
6,Vistara,1533,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060,Short
7,Vistara,1543,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060,Medium
8,GO_FIRST,1013,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954,Medium
9,GO_FIRST,1014,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954,Medium

In [ ]:
display(data.describe())
display(data.info())
display(data.dtypes)

              flight       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean     1088.336618      12.221021      26.004751   20889.660523
std       426.694820       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%       783.000000       6.830000      15.000000    4783.000000
50%      1142.000000      11.250000      26.000000    7425.000000
75%      1486.000000      16.170000      38.000000   42521.000000
max      1560.000000      49.830000      49.000000  123071.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   airline            300153 non-null  object
 1   flight             300153 non-null  int64
 2   source_city        300153 non-null  object
 3   departure_time     300153 non-null  object
 4   stops              300153 non-null  object
 5   arrival_time       300153 non-null  object
 6   destination_city   300153 non-null  object
 7   class              300153 non-null  object
 8   duration           300153 non-null  float64
 9   days_left          300153 non-null  int64
 10  price              300153 non-null  int64
 11  duration_category  300153 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

None

airline               object
flight                 int64
source_city           object
departure_time        object
stops                 object
arrival_time          object
destination_city      object
class                 object
duration             float64
days_left              int64
price                  int64
duration_category     object
dtype: object

In [ ]:
#data type conversion
cols_to_fix = ['airline','source_city','departure_time','stops','arrival_time','destination_city','class','duration_category']

data[cols_to_fix]=data[cols_to_fix].astype("string")
display(data.dtypes)
data.head()

airline              string[python]
flight                        int64
source_city          string[python]
departure_time       string[python]
stops                string[python]
arrival_time         string[python]
destination_city     string[python]
class                string[python]
duration                    float64
days_left                     int64
price                         int64
duration_category    string[python]
dtype: object

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,duration_category
0,SpiceJet,1408,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,Medium
1,SpiceJet,1387,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,Long
2,AirAsia,1213,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,Medium
3,Vistara,1559,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,Medium
4,Vistara,1549,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,Long

In [ ]:
from IPython.core.interactiveshell import dis
#checking for unique values relating to kenya
display(data['source_city'].unique())
display(data['destination_city'].unique())
display(data['airline'].unique())
display(data['class'].unique())
display(data['stops'].unique())
display(data['departure_time'].unique())

<StringArray>
['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai']
Length: 6, dtype: string

<StringArray>
['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi']
Length: 6, dtype: string

<StringArray>
['SpiceJet', 'AirAsia', 'Vistara', 'GO_FIRST', 'Indigo', 'Air_India']
Length: 6, dtype: string

<StringArray>
['Economy', 'Business']
Length: 2, dtype: string

<StringArray>
['zero', 'one', 'two_or_more']
Length: 3, dtype: string

<StringArray>
['Evening', 'Early_Morning', 'Morning', 'Afternoon', 'Night', 'Late_Night']
Length: 6, dtype: string